[package] name = "da-indexer-entity"
version = edition = "2021" publish = false
[lib] path = "src/lib.rs"
[dependencies] sea-orm = { version = "0.12.2", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros" ] }
